Fixed logic for steam-os and my_steam

diff --git a/my_steam b/my_steam
--- a/my_steam
+++ b/my_steam
@@ -7,11 +7,15 @@ if pgrep -f steam.sh > /dev/null
 then
 	echo "Steam is already started. Since you lost it, we'll find it for you."
 	steam &&
-		exit
+		exit 1
 	exit
 fi
 
-steam steam://open/bigpicture &
+# Fix for bug with Gnome Activities not allowing window switching with wmctrl
+dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.hide();'
+
+#steam steam://open/bigpicture &
+steam &
 
 sleep 1
 
@@ -26,36 +30,45 @@ do
 	fi
 done
 
-# Runs a script that uses a single monitor
-my_xrandr hdmi_only
-
 # Check if active window is steam
 # Sleep and then try to raise it if it is not
 # Try 3 times
 for i in $(seq 1 3)
 do
-	# Raise Steam window and then store which window is active
-	wmctrl -a Steam
-	sleep .5
-	windowid=$(xdotool getactivewindow)
-
-	if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
+	# Raise Steam window and if fails we notify
+	if [ ! "$(wmctrl -a Steam)" ]
 	then
+		echo "Steam not raised by our command, may already have focus"
+	fi
+
+	# Get active window and then see if it is Steam, otherwise loop again
+	windowid=$(xdotool getactivewindow)
+	activewindow="$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)"
+
+	if [[ "$activewindow" == "Steam" ]]
+	then
+		echo "We found Steam, it is our active window"
 		break # Steam is raised
 	fi
 
-	sleep 1
+	sleep 2
 	echo "Steam Big Picture not available or not raised, attempt number $i"
 done
+
+# We'll get the active window again
+windowid=$(xdotool getactivewindow)
+activewindow="$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)"
 
 # Send two Return keystrokes to Steam window ID
 # One to skip intro, one to login first account
 # Echo success or fail
-if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
+if [[ "$activewindow" == "Steam" ]]
 then
 	xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return || 
-		echo "xdotool exited oddly, did the window close?" && exit
+		echo "xdotool exited oddly, did the window close?" && exit 1
 	echo "Script done, you should be logged in!"
 else
 	echo "Something went wrong, skipping automatic login for Steam Big Picture!"
+	echo "Our active window was $activewindow"
+	exit 1
 fi
