Made Chromium script safer and better

diff --git a/personal_chrome b/personal_chrome
--- a/personal_chrome
+++ b/personal_chrome
@@ -32,14 +32,18 @@ then
 	echo "Odd, the directory isn't encrypted, we'll just pretend we didn't see this."
 	zenity --no-wrap --error --text="Somehow things were left unencrypted. Did the script exit normally?" --title="Warning!"
 else
-	echo The profile is missing, exiting to avoid damage.
-	zenity --no-wrap --error --text="I can't find the profile. Someday I will have logic to make the profile here." --title="Profile Not Found!"
-	exit
+	echo No profile found. Creating a new Chromium profile.
+#	echo The profile is missing, exiting to avoid damage.
+#	zenity --no-wrap --error --text="I can't find the profile. Someday I will have logic to make the profile here." --title="Profile Not Found!"
+#	exit
 fi
 
 chromium-browser --user-data-dir=.hidden_chromium/
 
-mv .chromiumprofile .chromiumprofile~
+if [ -f .chromiumprofile ]
+then
+	mv .chromiumprofile .chromiumprofile~
+fi
 
 echo "Okay, we exited. Let's hide the evidence."
 
@@ -50,19 +54,17 @@ rm -rf .hidden_chromium/*/Service\ Worker/CacheStorage
 rm -rf .hidden_chromium/ShaderCache
 rm -rf .hidden_chromium/*/Application\ Cache
 
-gpg-zip -c -o .chromiumprofile .hidden_chromium/
+gnome-terminal -- sh -c "cd ~/Documents ; gpg-zip -c -o .chromiumprofile .hidden_chromium/ && rm -rf .hidden_chromium"
 
-if [[ $? -ne 0 ]]
-then
-	echo "WTF, you messed up creating the file? We'll bail out of here so you don't break anything..."
-	zenity --no-wrap --error --text="Creation of the encrypted tarball failed. User Action is Required to Recover." --title="Fatal Error!"
-	exit
-fi
-
-rm -rf .hidden_chromium
-
-zenity --info --text "Everything has been encrypted." --title "Finished"
-
+#if [[ $? -ne 0 ]]
+#then
+#	echo "WTF, you messed up creating the file? We'll bail out of here so you don't break anything..."
+#	zenity --no-wrap --error --text="Creation of the encrypted tarball failed. User Action is Required to Recover." --title="Fatal Error!"
+#	exit
+#fi
+#
+#rm -rf .hidden_chromium
+#
 #echo "type \"y\" to delete the unencrypted chromium profile (.hidden_chromium)"
 #read stopstop
 #if [[ "$stopstop" == "y" ]]
