Logic change, sometimes failing

diff --git a/steam-autologin b/steam-autologin
--- a/steam-autologin
+++ b/steam-autologin
@@ -12,7 +12,7 @@ do
 	if ! netstat -lp 2>&1 | grep -i steam > /dev/null
 	then
 		sleep 2
-		echo "Steam not started yet (Steam network ports not reserved)"
+		echo "$i time waiting for Steam to start (Steam network ports not reserved)"
 	fi
 done
 
@@ -37,19 +37,15 @@ do
 	fi
 
 	sleep 1
-	echo "Steam window not available or not raised"
+	echo "Steam window not available or not raised, try number $i"
 	wmctrl -a Steam
 	sleep .5
 	windowid=$(xdotool getactivewindow)
 done
 
-# Check if the active window is Steam
-# If true, send two Return keystrokes
+# Sent two Return keystrokes to Steam window ID
 # One to skip intro, one to login first account
-if [[ "$(wmctrl -l | grep "$(printf '0x0%x' "$windowid")" | cut -b19-1000)" == "Steam" ]]
-then
-	xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return
-	echo "Script done, you should be logged in!"
-else
+# Echo success or fail
+xdotool key --window "$windowid" --delay 1000 --window "$windowid" Return key Return && 
+	echo "Script done, you should be logged in!" || 
 	echo "Something went wrong, not doing anything!"
-fi
